### ISSUE TITLE
php5 does not load

### ISSUE THREAD

**Issue by jlabonte** [e1ioan/rokuphp#1]
I tried following your instructions but it fails when trying to install php5. Apparently PHP5 is no longer easily available for install via your install.sh script. 

I have tired several alternate methods but still have not been able to get your software working on my raspberry pi 3.

When do you think you will have an update available to properly perform the install?

**Comment by e1ioan** [comment]
I'll check it later today and I'll let you know what I find.

**Comment by e1ioan** [comment]
Please try now. It should work fine. Let me know if you still have problems. Thanks.

**Comment by jlabonte** [comment]
Well that got the web application running. I was able to configure the cameras and the Roku to does recognizer the cameras I configured, but when I click on a camera to view the video it displays the following  message, "Cannot play this live stream..."

I checked the configuration and everything looks fine for ONVIF compliant cammeras. It is using the same rtsp url I use in AnyCam, so I know the link works.

**Comment by e1ioan** [comment]
First time, when you enter the Pi's IP in the Roku application, the list of cameras is shown, but it won't play. Exit the roku app, and start it again, see if you can play the stream then.

**Comment by jlabonte** [comment]
I removed the app from the Roku TV and then added it back in. I then rebooted/restarted the Roku TV. I then went in and added the PI's IP. 

The two cameras I have configured showed up in the list. However, when ever I click on either camera, the screen flashes the status bar like its going to show the camera image, but then it returns to the IP Camera Viewer Pro Menu.

I then restarted the Roku TV again, not it once again displays the message, "Cannot play this live stream..."

**Comment by e1ioan** [comment]
In a browser, go to:

http://your_raspberrypi_ip/getstream.php?cam=name of the camera

Then please look in the apache 2 logs and see if there are any ffmpeg errors. Please let me know what you find.

**Comment by jlabonte** [comment]
I did as requested, here is everything the error.log file:

[Tue Nov 07 00:18:21.490535 2017] [mpm_prefork:notice] [pid 3452] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Tue Nov 07 00:18:21.490740 2017] [core:notice] [pid 3452] AH00094: Command line: '/usr/sbin/apache2'
rm: cannot remove '/dev/shm/*': No such file or directory
[rtsp @ 0x103c550] Nonmatching transport in server reply
rtsp://480347:888888@10.253.161.140:554/onvif1: Invalid data found when processing input

**Comment by e1ioan** [comment]
It seems that your cameras only work with UDP and my application, by default tries to connect to the cameras using tcp. To fix the problem, please edit streamer.xml config file:

`sudo nano /var/www/html/config/streamer.xml`

edit the lines

`<infile_options>...</infile_options>`

and remove  `-rtsp_transport tcp`

**Comment by jlabonte** [comment]
Well that appears to have done the trick. You may want to add that as an option to the setup for the cameras.

Also one more thing. When I go to the settings on the IP Camera Viewer Pro and select "Split Screen View" the two camera I have configured via the PI don't show up as options under the "Split Screen Camera Selection Area". Should they are are PI cameras not available for split screen display?

**Comment by e1ioan** [comment]
I took the tcp as default protocol out, now ffmpeg will find what protocol works.

The split screen or screen saver do not support the HLS stream. Screen saver will never support it, Roku doesn't allow video of any kind in a screen saver. Split screen, I'm not sure yet, probably won't work, but I'm not 100% sure yet.

**Comment by jlabonte** [comment]
Fair enough. I appreciate your help getting this working. Not that it works I love it. I'm going to add more cameras shortly. I'm not concerns with the screen saver issue. If I want a full time display of one of my cameras, I would just go tot he IP Camera Viewer and display it. The few things that I have observed so far are:
1) Would be nice to have the split screen ability.
2) If no split screen, then the ability to have the app scroll through the feeds. Have the option to specify how long to delay on each camera.

Other than these items so far, it's working great now.

Thank You,
Jay LaBonte

**Comment by e1ioan** [comment]
Thank you for the feedback and reporting the issue. I will look into the split screen or the option to loop between cameras for next version.

**Comment by e1ioan** [comment]
If/when you are happy with the application, please rate it in the store... so far it seems that only people that don't like the app rated it.
