### ISSUE TITLE
FR For Roku IP Camera Pro: On launch show the last camera view

### ISSUE THREAD

**Issue by MrStevenFeldman** [e1ioan/rokuphp#11]
(not sure if there is a better place to make this request)

I would like it if when launching the roku IP camera pro channel it went directly to the last camera that was open the previous time the channel was open. This would make it easier for us to have our assistant device switch to the channel and show the camera without finding the TV remote.

**Comment by prtejada** [comment]
This would be a fantastic feature. I have been trying to automate the display on my TV but sometimes the Ruku slows down and it does get the enter command to select the first camera after launch. It would be great to just display the first camera automatically.

**Comment by e1ioan** [comment]
The feature is implemented. Next week, I hope, the new version is going to be published.

The new version can be configured to start to a specific camera or split screen. 
External Control Protocol (ECP) is also supported in the new version, to start to the view you'll like. Making a video doorbell that turns your tv on, to the camera you want it's possible now, for example.
