### ISSUE TITLE
Web interface replaced with php script

### ISSUE THREAD

**Issue by blackcomb-dev** [e1ioan/rokuphp#12]
I followed the guide as provided in README.md, with the php5 script clean installing with no errors and my Pi's IP address inputted into the relevant setting option on the Roku app. However, once I navigated to my Pi's IP in the web browser (both in Chrome 76 and IE 11), I was met with the following block of code instead of the web interface (see below). I tried the php7 script instead, which clean installed with no issues, and this time the browser returned an Error 500 code when I attempted to navigate to my Pi's IP address. Tested with both a Pi 1 Model B+ and a Pi 3 Model B, both running Raspbian.

`
<?php
require_once("rpcl/rpcl.inc.php");
require_once("dm.php");
require_once("dmauth.php");
//Includes
use_unit("jquerymobile/forms.inc.php");
use_unit("extctrls.inc.php");
use_unit("stdctrls.inc.php");
use_unit("jquerymobile/jmobile.inc.php");

//Class definition
class PageLogin extends MPage
{
    public $EditLoginUser = null;
    public $ButtonLogin = null;
    public $EditLoginPassword = null;
    public $LabelLLogin = null;
    public $LabelLPassword = null;
   public $MsgCreate = null;
   public $LabelCPasswor = null;
   public $LabelCRPassword = null;
   public $LabelCLogin = null;
   public $EditRePassword = null;
   public $EditPassword = null;
   public $EditLogin = null;
   public $ButtonCreateUser = null;
   public $LabelCTitle = null;
   function ShowHideCreateUser($val)
   {
     $this->MsgCreate->Visible = $val;
     $this->LabelCTitle->Visible = $val;
     $this->LabelCLogin->Visible = $val;
     $this->EditLogin->Visible = $val;
     $this->LabelCPasswor->Visible = $val;
     $this->EditPassword->Visible = $val;
     $this->LabelCRPassword->Visible = $val;
     $this->EditRePassword->Visible = $val;
     $this->ButtonCreateUser->Visible = $val;
   }
   function ShowHideLogin($val)
   {
     $this->LabelLLogin->Visible = $val;
     $this->EditLoginUser->Visible = $val;
     $this->LabelLPassword->Visible = $val;
     $this->EditLoginPassword->Visible = $val;
     $this->ButtonLogin->Visible = $val;
   }
   function ButtonCreateUserClick($sender, $params)
   {
      global $dm;
      $path = $dm->GetDataPath();
      if($this->EditLogin->Text == "")
      {
         $this->MsgCreate->Caption = "Login is required";
         return;
      }
      if($this->EditPassword->Text == "")
      {
         $this->MsgCreate->Caption = "Password is required";
         return;
      }
      if($this->EditPassword->Text != $this->EditRePassword->Text)
      {
         $this->MsgCreate->Caption = "Password does not match.";
         return;
      }
      $hash = md5($this->EditLogin->Text . ":rokuphp:" . $this->EditPassword->Text);
      if($fh = fopen($path . "validuser.txt", 'w'))
      {
         $stringData = $this->EditLogin->Text . ":rokuphp:" . $hash;
         fwrite($fh, $stringData, 1024);
         fclose($fh);
      }
      global $dmauth;
      $dmauth->ZAuth->UserName = $this->EditLoginUser->Text;
      $dmauth->ZAuth->UserPassword = $this->EditLoginPassword->Text;
      mobileRedirect("menu.php");
   }
    function PageLoginShow($sender, $params)
    {
      global $dm;
      $path = $dm->GetDataPath();
      $val = file_exists($path . "validuser.txt");
      $this->ShowHideCreateUser(!$val);
      $this->ShowHideLogin($val);
    }
    function ButtonLoginClick($sender, $params)
    {
      global $dmauth;
      $dmauth->ZAuth->UserName = $this->EditLoginUser->Text;
      $dmauth->ZAuth->UserPassword = $this->EditLoginPassword->Text;
      mobileRedirect("menu.php");
    }
}

global $application;

global $PageLogin;

//Creates the form
$PageLogin = new PageLogin($application);

//Read from resource file
$PageLogin->loadResource(__FILE__);

//Shows the form
$PageLogin->show();

?>
`

**Comment by blackcomb-dev** [comment]
Did I misconfigure something or miss something in the installation process?

**Comment by e1ioan** [comment]
Try installing the the other script, install.sh which is for php7

**Comment by blackcomb-dev** [comment]
@e1ioan I just tried it: the script completed with no errors, but when I attempted to navigate to my Pi's IP address in a web browser it returned 'HTTP ERROR 500'
![image](https://user-images.githubusercontent.com/30536280/63230420-35626300-c1c1-11e9-9432-3c0108d86a4f.png)

**Comment by drvrtigo** [comment]
After a bit of searching, it seems to be an issue with PHP versions > 7.2 (https://www.php.net/manual/en/reserved.other-reserved-words.php)

`Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/html/rpcl/system.inc.php on line 77`

**Comment by blackcomb-dev** [comment]
@drvrtigo @e1ioan I can confirm that on my end the issue with the php7 script was resolved once I modified the script to install php7.1 and its derived tools rather than php v7.3

**Comment by e1ioan** [comment]
@blackcomb-dev What modification did you make in the install script or how exactly did you install php7.1? `sudo apt-get install php7.1`? I will make the modifications in the install script if you let me know what worked.

**Comment by e1ioan** [comment]
Thanks @blackcomb-dev 
Modified the script to install php7.1
