### ISSUE TITLE
New install can't save new user id

### ISSUE THREAD

**Issue by jace055** [e1ioan/rokuphp#13]
Just did an install following the directions.  On the initial login screen I can't click save user.  I have tried on a few different devices and web browsers.

**Comment by bunit17** [comment]
I am also having the same issue, opted for clean install using standard PHP 7 install. Can't set a new user account. Looking in Chrome console looks like jQuery is not picked up.

**Comment by e1ioan** [comment]
I will try again a clean install on my raspberry, I'll let you know what I find out.

**Comment by e1ioan** [comment]
Found the problem, trying to fix it now.

**Comment by e1ioan** [comment]
Fixed. Please re run the install script.

**Note:** Make sure to fully refresh the webpage in browser to load the new jquery.

**Note 2:** Please let me know if this is fixed on your side too.

**Comment by jace055** [comment]
Thanks e1ioan!  This issue is fixed.
