### ISSUE TITLE
rtsp not working for EZVIZ camera

### ISSUE THREAD

**Issue by nmummau** [e1ioan/rokuphp#14]
**What I'm dealing with**
I have one of these budget cameras that I'd like to cast to my Roku TV. Fortunately the Roku echo system has your app, but unfortunately it doesn't seem to support the rtsp stream of this camera.

**Camera Details**
EZVIZ 720P Wi-Fi Cloud Camera
Model#: CS-CV206 (Mini O)
Date: 12/2018

[EZVIZ recently published documentation](https://community.ezvizlife.com/hc/en-us/articles/360034827754-How-to-configure-RTSP-stream-) describing how to setup the rtsp stream of these cameras. And it works great using VLC or the basic Ubuntu video player.
However, I've been unsuccessful to set this stream up with your Roku Basic app. 

On the bottom of the camera is a password (we'll call it ABC123).
EZVIZ's instructions tell you to use that password and the IP address of your camera to create the rtsp URI. It looks like this for me: rtsp://admin:ABC123@192.168.1.56

**What I've Tried**
I've tried a combination of things in your app's "Edit Camera Information" screen. No success:
- Setting the IP, Login, Password does not work.
- Scanning results in the message: " MJPEG | No MJPEG URIs were found"
- EZVIZ is not a supported brand in the brand selector.
- Entering "rtsp://admin:ABC123@192.168.1.56" as the Stream URL does not work.

**Comment by e1ioan** [comment]
The Roku application supports rtsp streams ONLY if they are jpeg encoded. I'm guessing that your camera only provides h264 streams. To be able to see a h264 stream you need to follow the guide here on github, you'll need a raspbery pi (or orange pi) and setup the software to decode the stream.

**Comment by nmummau** [comment]
Thanks for the explanation. I was convinced I was missing something.

**Comment by e1ioan** [comment]
One thing that you can do to make it work - if your camera has a snapshot feature - link in the application on Roku the snapshot url. You will be able to see the camera, but the FPS will be low.

**Comment by alanrenouf** [comment]
@nmummau I know this is an old thread but did you get it working? I installed everything on this page and the rtsp link works fine in VLC but I get nothing from the pi app
