### ISSUE TITLE
Split screen on Roku

### ISSUE THREAD

**Issue by PythonNube** [e1ioan/rokuphp#19]
When I add cameras to my RaspberryPi they do show up in the ROKU app but I am not able to select them for the split screen view.  It seems like the settings menu does not recognize the cameras that are set up on the RaspberryPI.  I wanted to show a split screen view of two RSTP camera feeds on the Roku at the same time.  Any help would be excellent.

**Comment by e1ioan** [comment]
This is a Roku limitation. You cannot play two h264 videos at the same time, Roku has only one hardware decoder for h264.
