### ISSUE TITLE
Question: How can BlueIris new RTSP streams can be added into the Roku app

### ISSUE THREAD

**Issue by goldriver2** [e1ioan/rokuphp#20]
Hi

I have not been able to find any email or ways to contact you otherwise, I am wondering, with the new BlueIris 5.3, we have the opportunitioes to broadcast all configured cameras via RTSP

is there any way to directly configure the Roku app without the rokuphp to stream thoses RTSP with sound ?

**Comment by e1ioan** [comment]
No, Roku doesn't support rtsp streaming for h264 streams, it only supports HLS, so the raspberry pi is necessary to convert rtsp stream into HLS.
