### ISSUE TITLE
Launching the purchased app is asking for the app to be purchased again

### ISSUE THREAD

**Issue by mgardner1969** [e1ioan/rokuphp#27]
In trying to launch the app, it is indicating it must be purchased again.  I have tried removing it from Roku and purchasing it again only to be again prompted to purchase the app.

**Comment by wd8rde** [comment]
I am having this issue as well, initially only on my Roku 3920X, no problem with my 4630X. But later in the day today the 4630X started to do it too. So now all our cameras are down.

**Comment by e1ioan** [comment]
It seems that there is a problem with lots of applications from Roku. I
reported the problem and we are waiting for an answer from them. I'll let
you know when I know more.

**Comment by mgardner1969** [comment]
You can fix the issue by doing an update to the Roku itself.

**Comment by wd8rde** [comment]
So that was weird. Settings->System->Update System. Mine was already fully up to date, it came back and said that no updates were needed. But after that the IP Camera channel worked again. Shows that even no update needed has some effect ...

**Comment by mgardner1969** [comment]
Same here but it worked on all five of my Rokus
