### ISSUE TITLE
Split Screen View

### ISSUE THREAD

**Issue by kgtpuck** [e1ioan/rokuphp#3]
I have everything implemented pretty successfully.  RasperryPi is happy with a static IP.  Cameras added.  Streams verified in VLC.

4 cameras I have show up automatically on the home screen of IP Camera Viewer when I add the PiIP address.  However, there are no cameras showing up in the "settings" page.  Therefore I cannot add a Split Screen View.

I can view each camera individually from the home screen, but no luck with the split screen.

Any ideas?

**Comment by e1ioan** [comment]
There is no split screen view when using h264 and that is a limitation of the Roku device, it can only decode and show one h264 stream at a time.

**Comment by kgtpuck** [comment]
Thanks!  It would be a great feature for Roku to sort out.
