### ISSUE TITLE
Can't access the Pi IP

### ISSUE THREAD

**Issue by MrGingerManBread** [e1ioan/rokuphp#42]
When I try to navigate to the Pi's address the page is all white and won't load anything

**Comment by MrGingerManBread** [comment]
I’ve tried Chrome, Firefox, Edge, IE on Windows 11. I’ve tried Chrome and Safari on iOS. The page is white and nothing loads. I’ve tried reinstalling the OS and currently have it in the headless configuration. Nothing shows me the login page like your guide shows. 

The OS currently loaded is Raspberry Pi OS Lite 64-bit (Bookworm) 24-07-04

**Comment by yachty-by-nature** [comment]
you need to edit the install.sh file to install the 7.3 version of PHP.  It's the only version that seems to work with this

**Comment by MrGingerManBread** [comment]
Thanks so much! You totally saved my bacon with your advice and instructions @ https://github.com/e1ioan/rokuphp/issues/43#issue-2476719911
