### ISSUE TITLE
no web interface

### ISSUE THREAD

**Issue by kw4m** [e1ioan/rokuphp#8]
when I type the ip address in my browser I get a blank screen.  When I enter http://192.168.86.43/index.php manually I get a screen full of programming. 

<?php
require_once("rpcl/rpcl.inc.php");
require_once("dm.php");
require_once("dmauth.php");
//Includes
use_unit("jquerymobile/forms.inc.php");
use_unit("extctrls.inc.php");
use_unit("stdctrls.inc.php");
use_unit("jquerymobile/jmobile.inc.php");

//Class definition
class PageLogin extends MPage
{
    public $EditLoginUser = null;
    public $ButtonLogin = null;
    public $EditLoginPassword = null;
    public $LabelLLogin = null;
    public $LabelLPassword = null;
   public $MsgCreate = null;
   public $LabelCPasswor = null;
   public $LabelCRPassword = null;
   public $LabelCLogin = null;
   public $EditRePassword = null;
   public $EditPassword = null;
   public $EditLogin = null;
   public $ButtonCreateUser = null;
   public $LabelCTitle = null;
   function ShowHideCreateUser($val)
   {
     $this->MsgCreate->Visible = $val;
     $this->LabelCTitle->Visible = $val;
     $this->LabelCLogin->Visible = $val;
     $this->EditLogin->Visible = $val;
     $this->LabelCPasswor->Visible = $val;
     $this->EditPassword->Visible = $val;
     $this->LabelCRPassword->Visible = $val;
     $this->EditRePassword->Visible = $val;
     $this->ButtonCreateUser->Visible = $val;
   }
   function ShowHideLogin($val)
   {
     $this->LabelLLogin->Visible = $val;
     $this->EditLoginUser->Visible = $val;
     $this->LabelLPassword->Visible = $val;
     $this->EditLoginPassword->Visible = $val;
     $this->ButtonLogin->Visible = $val;
   }
   function ButtonCreateUserClick($sender, $params)......

**Comment by e1ioan** [comment]
It means that php didn't install. If you run the php5 script, try the php7 (or the other way around).
